import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import { Suspense } from "react";
import ClientWrapper from "./clientWrapper";
import StoreProvider from "./redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Project Management",
  description: "Generated by create next app",
  icons: { icon: "/logo.png" },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <StoreProvider>
          <Suspense fallback={<div>Loading...</div>}>
            <NextTopLoader />
            <ClientWrapper>{children}</ClientWrapper>
          </Suspense>
        </StoreProvider>
      </body>
    </html>
  );
}
